MYblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/urls.py
# coding=UTF-8
from django.conf.urls import url
from . import views

#视图函数命名空间
app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexViews.as_view(), name='index'),
	#(?P<pk>[0-9]+)命名捕获组，从用户访问的URL里把括号内匹配的字符串捕获并作为关键字参数传给其对应的views函数detail
	#例如用户访问past/255/，事实上detail调用时是这样：detail(request, pk=255)
	#这就是在URL中捕获文章的id
	url(r'^posts/$', views.PostsViews.as_view(), name='posts'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
	#括号括起来的是命名组参数，django会从用户访问的URL中提取这两个参数的值，然后传递给其对应的视图函数。
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesViews.as_view(), name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryViews.as_view(), name='category'),
	url(r'^author/(?P<pk>[0-9]+)/$', views.author, name='author'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag')
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
# coding:UTF-8

import markdown
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags


class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Post(models.Model):
	# 标题
	title = models.CharField(max_length=100)
	# 文章
	body = models.TextField()
	# 创建时间
	created_time = models.DateTimeField()
	# 修改时间
	modified_time = models.DateTimeField()
	# 文章摘要
	excerpt = models.CharField(max_length=200, blank=True)
	# 分类，一对多
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	# 标签，多对多
	tag = models.ManyToManyField(Tag)
	# 作者，一对多
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	# 阅读量
	views = models.PositiveIntegerField(default=0)

	def save(self, *args, **kwargs):
		if not self.excerpt:
			# 首先实例化一个markdown类
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				'markdown.extensions.toc',
				])
			# 先将 markdown文本渲染成 html文本
			# strip_tags去掉 html文本的全部 html标签
			# 从文本中截取前54个字符赋予 excerpt
			self.excerpt = strip_tags(md.convert(self.body))[:54]

		super(Post, self).save(*args, **kwargs)

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		# blog应用下的name=detail（urls.py）,pk在这里就是id
		# 找到对应视图函数，传入参数pk替换urls中的正则表达式，再返回，生成POST自己的URL
		return reverse('blog:detail', kwargs={'pk': self.pk})
	# django允许我们在models.Model的子类里定义一个Meta内部类

	class Meta:
		'''
		这个内部类通过指定一些属性来规定这个类该有的一些特性
		ordering属性用来指定文章的排序方式，先按照created_time的反序排列，created_time相同再按照标题排序
		'''
		ordering = ['-created_time', 'title']

comments/models.py
from django.db import models


class Comment(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	url = models.URLField(blank=True)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	#blog应用中的models.Post类
	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

	def __str__(self):
		return self.text[:20]

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentForm
from .models import Post, Category, Tag
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

# Create your views here.


# def index(request):
#     post_list = Post.objects.all()
#     context = {
#         'post_list': post_list,
#     }
#     return render(request, 'blog/index.html', context=context)
class IndexViews(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	# 指定 paginate_by 属性后开启分页功能,其值代表每一页包含的文章数
	paginate_by = 5

	def get_context_data(self, **kwargs):
		'''
		在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的,
		例如 render(request, 'blog/index.html', context={'post_list': post_list}),
		这里传递了一个 {'post_list': post_list} 字典给模板.
		在类视图中,这个需要传递的模板变量字典是通过 get_context_data 方法获得的,
		所以我们覆写该方法,以便我们能够自己再插入一些我们自定义的变量进去.
		'''

		# 首先获得父类生成的传递给模板的字典
		context = super().get_context_data(**kwargs)

		'''
		父类生成的字典中已有了 paginator/page_obj/is_paginated 这三个模板变量
		paginator 是 Paginator 的一个实例(分页实例)
		page_obj 是 Page 的一个实例(当前分页实例)
		is_paginated 是一个布尔变量,指示是否分页
		由于 context 是一个字典,所以用 get 方法从中取出某个键对应的值
		'''
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

		# 调用自己写的 pagination_data 方法获得显示分页导航条需要得数据
		pagination_data = self.pagination_data(paginator, page, is_paginated)

		# 将分页导航条的模板变量更新到 context 中,注意 pagination_data 方法返回的也是一个字典
		context.update(pagination_data)

		# 将更新后的 context 返回,以便 ListView 使用这个字典中的模板变量去渲染模板.
		# 注意此时 context 字典中已有了显示分页导航条所需的数据
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}
		# 当前页左边连续的页码号,初始值为空
		left = []
		# 当前页右边连续的页码数,初始值为空
		right = []
		# 标示第一页页码后是否需要显示省略号
		left_has_more = False
		# 标示最后一页页码前是否需要显示省略号
		right_has_more = False
		# 标示是否需要显示最后一页页码号
		# 因为如果当前页左边的连续页码中已经含有第一页的页码,此时就无需再显示第一页的页码了
		# 其他情况下第一页页码默认显示
		# 初始值为 False
		first = False
		# 同上,标示变量
		last = False

		# 获得用户当前请求的页码数
		page_number = page.number

		# 获得分页后的总页数
		total_pages = paginator.num_pages

		# 获得整个分页页码列表, 比如分了4页,那就是[1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:
			'''
			如果用户当前请求第一页,那么当前页左边就不需要数据,因此left = [](默认)
			此时只需要获取当前页右边的连续页码数, right = [2, 3, 4, 5]
			后面的数字表示截取的范围
			'''
			right = page_range[page_number:page_number + 2]

			# 如果最右边的页码号比最后一页的页码号减去1还要少,
			# 说明最右边的页码号和最后一页的页码号之间还有其他页码,因此需要省略号,通过 right_has_more 来指示

			if right[-1] < total_pages - 1:
				right_has_more = True

			# 如果最右边的页码比最后一页的页码小,说明当前页右边的连续页码中不包含最后一页页码
			# 所以需要显示最后一页的页码,用 last 来标示

			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			'''
			如果用户请求的是最后一页的数据,那么当前页右边就不需要数据,因此 right = []
			此时只要获取左边的联系页码
			截取左边连续2个页码,如果剩下的页码数不足2个,则从头开始截取
			'''
			left = page_range[(page_number - 3)
							  if (page_number - 3) > 0 else 0:page_number - 1]

			# 如果最左边的页码比第2页的页码大,说明当前页左边需要省略号
			if left[0] > 2:
				left_has_more = True

			# 如果最左边的页码比第一页大,说明需要显示第一页页码
			if left[0] > 1:
				first = True

		else:
			# 用户请求的既不是第一页也不是最后一页,怎需要显示两边的页码
			left = page_range[(page_number - 3)
							  if (page_number - 3) > 0 else 0:page_number - 1]

			right = page_range[page_number:page_number + 2]

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			# 是否需要显示第一页和第一页后的省略号
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
		}

		return data


# def posts(request):
#     post_list = Post.objects.all()
#     context = {
#         'post_list': post_list,
#     }
#     return render(request, 'blog/full-width.html', context=context)
class PostsViews(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'


def about(request):
	return render(request, 'blog/about.html')


def contact(request):
	return render(request, 'blog/contact.html')


# 根据从url中捕获的id（pk）获取数据库中文章的id
# def detail(request, pk):
# 	# 传入的pk在数据库中存在就返回对应的post，不存在就返回404
# 	post = get_object_or_404(Post, pk=pk)
# 	# 阅读量+1
# 	post.increase_views()
# 	# extensions允许markdown支持额外的扩展，extra更多的扩展，codehilite代码高亮，toc自动生成目录
# 	post.body = markdown.markdown(post.body,
# 								  extensions=[
# 									  'markdown.extensions.extra',
# 									  'markdown.extensions.codehilite',
# 									  'markdown.extensions.toc',
# 								  ])
# 	form = CommentForm()
# 	comment_list = post.comment_set.all()
# 	context = {
# 		'post': post,
# 		'form': form,
# 		'comment_list': comment_list,
# 	}
# 	return render(request, 'blog/detail.html', context=context)
class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	context_object_name = 'post'

	# 可以简单地认为是 detail 视图函数的调用
	def get(self, request, *args, **kwargs):
		'''
		覆写此方法的目的是因为每当文章被访问一次,阅读量就+1
		get 方法返回一个 HttpResponse 实例
		之所以要调用父类的 get 是因为只有当 get 被调用后才有 self.object属性,其值为 Post 模型实例,即被访问的文章 post
		'''
		responese = super(PostDetailView, self).get(request, *args, **kwargs)

		# 将文章阅读量+1 self.object 就是被访问的文章
		self.object.increase_views()

		# 视图必须返回一个 HttpResponse 对象
		return responese

	# 对应 detail 视图函数中根据 pk(id) 获取文章,然后对文章的 post.body 进行 markdown 渲染
	def get_object(self, queryset=None):
		# 覆写 get_object 方法为了对 post.body 进行 markdown 渲染
		post = super(PostDetailView, self).get_object(queryset=None)
		md = markdown.Markdown(extensions=[
			'markdown.extensions.extra',
			'markdown.extensions.codehilite',
			TocExtension(slugify=slugify)
		])

		post.body = md.convert(post.body)
		post.toc = md.toc

		return post

	def get_context_date(self, **kwargs):
		# 覆写 get_context_date 方法,因为除了要把 post 传给模板( DetailView 已经帮我们完成)之外,还要把评论表单,post 下的传过去
		context = super(PostDetailView, self).get_context_date(**kwargs)
		form = CommentForm()
		comment_list = self.object.comments_set.all()
		context.update({
			'form': form,
			'comment_list': comment_list
		})
		return context


# 归档页面
'''
def archives(request, year, month):
  # created_time是django的date对象，里面有__year和__month属性，python调用类的属性一般是created_time.year
  # 但是这里作为参数传入，django规定要用__替代.
  post_list = Post.objects.filter(created_time__year=year,
								  created_time__month=month
								  ).order_by('-created_time')
  # 因为归档下的文章列表显示和主页是一样的，所以直接渲染index.html
  return render(request, 'blog/index.html', context={'post_list': post_list})
'''


class ArchivesViews(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesViews, self).get_queryset().filter(created_time__icontains="%s-0%s" %(year, month)).order_by('-created_time')


'''
分类页面,这里的pk是被访问分类的id
def category(request, pk):
	cate = get_object_or_404(Category, pk=pk)
	post_list = Post.objects.filter(category=cate)
	return render(request, 'blog/index.html', context={'post_list': post_list})
'''


class CategoryViews(ListView):
	model = Post
	template_name = 'blog/full-width.html'
	context_object_name = 'post_list'

	# 复写 ListView 的 get_queryset 方法，该方法默认返回制定 model 的全部列表数据
	def get_queryset(self):
		# 首先根据 url 捕获的分类 id（pk）获取分类，在类视图中，捕获的命名组参数值保存在实例的 kwargs 属性中（字典）
		# 非命名组参数保存在 agrs（列表）中,所以使用 self.kwargs.get()获取pk值。
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		# 调用父类的 get_queryset()获取全部列表数据，然后再 filter()
		return super(CategoryViews, self).get_queryset().filter(category=cate)


# 作者页面跟分类类似
def author(request, pk):
	post_list = Post.objects.filter(author=pk)
	return render(request, 'blog/index.html', context={'post_list': post_list})


def tag(request, pk):
	tag = get_object_or_404(Tag, pk=pk)
	post_list = Post.objects.filter(tag=tag)
	return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/about.html
{% extends 'base-full.html' %}
{% block main %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="http://ov2unu1uw.bkt.clouddn.com/17-9-7/87112763.jpg" alt="Developer Image">
								</figure>
								<p>人生苦短,我用Python.</p>
								<p>予时间以生活,给岁月以文明.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
{% endblock main %}

templates/blog/contact.html
{% extends 'base-full.html' %}
{% block main %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href=""{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="{% url 'blog:author' post.author.pk %}">{{ post.author }}</a></span>
                            <!-- <span class="comments-link"><a href="#">4 评论</a></span> -->
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!-- safe是django自带的过滤器作用于模版变量  -->
                        {{ post.body|safe }}
                    </div>
                </article>
<!--                 <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_lable }}">名字：</label>
                                {{ form.name }}
                                {{  form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_lable }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_lable }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_lable }}">评论：</label>
                                {{ form.text }}
                                {{ fom.text }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div> -->    <!-- row -->
<!--                     </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            <li>暂无评论...</li>
                            {% endfor %}
                        </ul>
                    </div>
                </section> -->
    {% endblock main %}
            <aside class="col-md-4">
                {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
    {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>

templates/blog/full-width.html
{% extends 'base-full.html' %}
{% block main %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						{% for post in post_list %}
						<article class="post post-{{ post.pk }}">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>

									<span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date">{{ post.created_time }}</time></a></span>

									<span class="post-author"><a href="{% url 'blog:author' post.author.pk %}">{{ post.author }}</a></span>

									<span class="comments-link"><a href="">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{ post.excerpt }}</p>
								<div class="read-more cl-effect-14">
									<a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
						{% empty %}
						<div class="no-post">暂时还没有发布的文章！</div>
						{% endfor %}
					</main>
				</div>
			</div>
		</div>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
			{% for post in post_list %}
				<article class="post post-{{ post.pk }}">
					<header class="entry-header">
						<h1 class="entry-title">
							<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
						</h1>
						<div class="entry-meta">
							<span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></span>
							<span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date">{{ post.created_time }}</time></a></span>
							<span class="post-author"><a href="{% url 'blog:author' post.author.pk %}">{{ post.author }}</a></span>
							<!-- <span class="comments-link"><a href="#">4 评论</a></span> -->
							<span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
						</div>
					</header>
					<div class="entry-content clearfix">
						<p> {{ post.excerpt }}...</p>
						<div class="read-more cl-effect-14">
							<a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
						</div>
					</div>
				</article>
			{% empty %}
					<div class="no-post">暂时还没有发布的文章！</div>
			{% endfor %}

<!-- 				简单分页效果
				{% if is_paginated %}
				<div class="pagination-simple">
					{% if page_obj.has_previous %}
					<a href="?page={{ page_obj.previous_page_number }}">上一页</a>
					{% endif %}
					<span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
					{% if page_obj.has_next %}
					<a href="?page={{ page_obj.next_page_number }}">下一页</a>
					{% endif %}
				</div>
				{% endif %}
 -->
				{% if is_paginated %}
				<div class="pagination">
					<ul>
						{% if first %}
						<li><a href="?page=1">1</a></li>
						{% endif %}
						{% if left %}
							{% if left_has_more %}
								<span>...</span>
							{% endif %}
							{% for i in left %}
							<li><a href="?page={{ i }}">{{ i }}</li>
							{% endfor %}
						{% endif %}
						<li class="current"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
						{% if right %}
							{% for i in right %}
							<li><a href="?page={{ i }}">{{ i }}</a></li>
							{% endfor %}
							{% if right_has_more %}
							<span>...</span>
							{% endif %}
						{% endif %}
						{% if last %}
						<li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
						{% endif %}
					</ul>
				</div>
			{% endif %}
{% endblock main %}