MYblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/urls.py
# coding=UTF-8
from django.conf.urls import url
from . import views

#视图函数命名空间
app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexViews.as_view(), name='index'),
	#(?P<pk>[0-9]+)命名捕获组，从用户访问的URL里把括号内匹配的字符串捕获并作为关键字参数传给其对应的views函数detail
	#例如用户访问past/255/，事实上detail调用时是这样：detail(request, pk=255)
	#这就是在URL中捕获文章的id
	url(r'^posts/$', views.PostsViews.as_view(), name='posts'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
	#括号括起来的是命名组参数，django会从用户访问的URL中提取这两个参数的值，然后传递给其对应的视图函数。
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesViews.as_view(), name='archives'),
	url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryViews.as_view(), name='category'),
	url(r'^author/(?P<pk>[0-9]+)/$', views.author, name='author'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag')
]

templates/base-full.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Any &amp; Nothing</title>
	<style>
		span.highlights {
			color: red;
		}
	</style>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>
	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Any</b> &amp; Nothing</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="主页">主页</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:posts' %}" data-hover="博客">博客</a></li>
    								<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
    								<!-- <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li> -->
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
{% block main %}
{% endblock main %}
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'blog:index' %}">主页</a></li>
					<li><a href="{% url 'blog:posts' %}">博客</a></li>
					<li><a href="about.html">关于</a></li>
					<li><a href="contact.html">联系</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>Any &amp; Nothing</title>
	<style>
		span.highlighted {
			color: red;
		}
	</style>

	<!-- meta -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- css -->
	<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

	<!-- js -->
	<script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'blog/js/pace.min.js' %}"></script>
	<script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
	<header id="site-header">
		<div class="row">
			<div class="col-md-4 col-sm-5 col-xs-8">
				<div class="logo">
					<h1><a href="{% url 'blog:index' %}"><b>Any</b> &amp; Nothing</a></h1>
				</div>
			</div><!-- col-md-4 -->
			<div class="col-md-8 col-sm-7 col-xs-4">
				<nav class="main-nav" role="navigation">
					<div class="navbar-header">
						<button type="button" id="trigger-overlay" class="navbar-toggle">
							<span class="ion-navicon"></span>
						</button>
					</div>

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
							<li class="cl-effect-11"><a href="{% url 'blog:posts' %}" data-hover="博客">博客</a></li>
							<li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
							<!-- <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li> -->
						</ul>
					</div><!-- /.navbar-collapse -->
				</nav>
				<div id="header-search-box">
					<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
					<div id="search-form" class="search-form">
						<form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
							<input type="search" name='q' placeholder="搜索" required>
							<button type="submit"><span class="ion-ios-search-strong"></span></button>
						</form>
					</div>
				</div>
			</div><!-- col-md-8 -->
		</div>
	</header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
	<div class="container">
		<div class="row">
			<main class="col-md-8">
			{% block main %}
			{% endblock main %}
			</main>
			<aside class="col-md-4">
			{% block toc %}
			{% endblock toc %}
				<div class="widget widget-recent-posts">
					<h3 class="widget-title">最新文章</h3>
					{% get_recent_posts as recent_post_list %}
					<ul>
						{% for post in recent_post_list %}
						<li>
							<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
						</li>
					{% empty %}
					<li>暂无文章...</li>
					{% endfor %}
					</ul>
				</div>
				<div class="widget widget-archives">
					<h3 class="widget-title">归档</h3>
					{% archives as date_list %}
					<ul>
						{% for date in date_list %}
						<li>
						<!--解析视图函数blog:archives对应的URL模式，并把年和月替换成date.year和data.month的值-->
							<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年 {{ date.month }} 月</a>
						</li>
						{% empty %}
						暂无归档...
						{% endfor %}
					</ul>
				</div>

				<div class="widget widget-category">
					<h3 class="widget-title">分类</h3>
					{% get_categorys as category_list %}
					<ul>
						{% for category in category_list %}
						<li>
							<a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
						</li>
					{% empty %}
					<li>暂无分类...</li>
					{% endfor %}
					</ul>
				</div>

				<div class="widget widget-tag-cloud">
					<h3 class="widget-title">标签云</h3>
					{% get_tag_list as tag_list %}
					<ul>
						{% for tag in tag_list %}
						<li>
							<a href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a>
						</li>
						{% empty %}
						<li>暂无标签...</li>
						{% endfor %}
					</ul>
				</div>
				<div class="rss">
					<a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
				</div>
			</aside>
		</div>
	</div>
</div>
<footer id="site-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
														target="_blank" title="模板之家">模板之家</a>
					- 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
				</p>
			</div>
		</div>
	</div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
	<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
	<nav>
		<ul>
			<li><a href="{% url 'blog:index' %}">首页</a></li>
			<li><a href="{% url 'blog:posts' %}">博客</a></li>
			<li><a href="{% url 'blog:about' %}">关于</a></li>
			<li><a href="{% url 'blog:contact' %}">联系</a></li>
		</ul>
	</nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>